// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoption.API.Data;

#nullable disable

namespace PetAdoption.API.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20240115154404_Change image url")]
    partial class Changeimageurl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buddy is a friendly and playful Golden Retriever, known for being great with kids",
                            Gender = 0,
                            Image = "img_1.jpg",
                            IsActive = true,
                            Name = "Buddy",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = 1,
                            Breed = "Cat - Siamese",
                            DateOfBirth = new DateTime(2021, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Whiskers is an elegant Siamese cat.",
                            Gender = 1,
                            Image = "img_2.jpg",
                            IsActive = true,
                            Name = "Whiskers",
                            Price = 150.0,
                            Views = 2
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = 1,
                            Breed = "Dog - German Shapherd",
                            DateOfBirth = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a friendly and playful German Shapherd, known for being great with kids",
                            Gender = 0,
                            Image = "img_3.jpg",
                            IsActive = true,
                            Name = "Rocky",
                            Price = 400.0,
                            Views = 3
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = 1,
                            Breed = "Rabbit - Himalayan",
                            DateOfBirth = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a friendly and playful Rabbit, known for being great with kids",
                            Gender = 1,
                            Image = "img_4.jpg",
                            IsActive = true,
                            Name = "Luna",
                            Price = 100.0,
                            Views = 1
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = 2,
                            Breed = "Dog - Jack Russel",
                            DateOfBirth = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jack is an elegant Jack Russel dog, known for being great with kids.",
                            Gender = 1,
                            Image = "img_5.jpg",
                            IsActive = false,
                            Name = "Jack",
                            Price = 650.0,
                            Views = 2
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = 0,
                            Breed = "Cat - Maias",
                            DateOfBirth = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maia is a friendly and playful Maias cat, known for being great with kids",
                            Gender = 0,
                            Image = "img_6.jpg",
                            IsActive = true,
                            Name = "Maia",
                            Price = 550.0,
                            Views = 10
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = 1,
                            Breed = "Rabbit - Himalayan",
                            DateOfBirth = new DateTime(2020, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Raffy is a friendly and playful Rabbit, known for being great with kids",
                            Gender = 0,
                            Image = "img_7.jpg",
                            IsActive = false,
                            Name = "Raffy",
                            Price = 150.0,
                            Views = 5
                        });
                });

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.UserAdoption", b =>
                {
                    b.HasOne("PetAdoption.Shared.Models.EntityModels.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Shared.Models.EntityModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetAdoption.Shared.Models.EntityModels.UserFavorites", b =>
                {
                    b.HasOne("PetAdoption.Shared.Models.EntityModels.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Shared.Models.EntityModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
